---
driver:
  name: vagrant
transport:
  ssh_key: "/root/chef-repo-drj/chef-repo/.chef/drj444.pem"
  username: vagrant
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04-i386
  - name: centos-6.7-i386

suites:
  - name: default
    run_list:
      - recipe[webserver]
      - recipe[log]
    attributes:
