---
driver:
  name: vagrant
transport:
  ssh_key: "/root/chef-repo-drj/chef-repo/.chef/drj444.pem"
  username: vagrant
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[webserver]
      - recipe[log]
    attributes:
