Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-6.7-i386"
  config.vm.network "private_network", type: "dhcp"
  config.omnibus.chef_version = :latest
  config.vm.provision :chef_client do |chef|
    chef.provisioning_path = "/etc/chef"
    chef.chef_server_url = "https://api.chef.io/organizations/unigo4"
    chef.validation_key_path = "/root/chef-repo-drj/chef-repo/.chef/drj444.pem"
    chef.validation_client_name = "drj444"
    chef.node_name = "centos-server"
#    chef.add_recipe "webserver"
    chef.add_recipe "log"
  end
end
